### ISSUE TITLE
Jellyfin 10.9.9 Erro When Seting UP the Pliging (After restart)

### ISSUE THREAD

**Issue by mofakhar** [Kevinjil/Jellyfin.Xtream#128]
When trying to use the plugin, I can get the list of TV, Series...etc; but nothing happening and in the log I'm getting the following error:
[2024-09-20 22:33:34.924 +00:00] [ERR] Error while sending discovery message
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendToAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.SendToAsync(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, EndPoint remoteEP, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.DiscoverDevices(Int32 discoveryDurationMs, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.DiscoverDevices(Int32 discoveryDurationMs, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.TunerHosts.TunerHostManager.DiscoverDevices(ITunerHost host, Int32 discoveryDurationMs, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.LiveTv.TunerHosts.TunerHostManager.DiscoverDevices(ITunerHost host, Int32 discoveryDurationMs, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.TunerHosts.TunerHostManager.ScanForTunerDeviceChanges(ITunerHost host, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.LiveTv.TunerHosts.TunerHostManager.ScanForTunerDeviceChanges(ITunerHost host, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.TunerHosts.TunerHostManager.ScanForTunerDeviceChanges(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.LiveTv.TunerHosts.TunerHostManager.ScanForTunerDeviceChanges(CancellationToken cancellationToken)
   at Jellyfin.LiveTv.Guide.GuideManager.RefreshGuide(IProgress`1 progress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.LiveTv.Guide.GuideManager.RefreshGuide(IProgress`1 progress, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.Guide.RefreshGuideScheduledTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.<>c__DisplayClass53_0.<<Execute>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.<>c__DisplayClass53_0.<Execute>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---
   at Jellyfin.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.DiscoverDevices(Int32 discoveryDurationMs, CancellationToken cancellationToken)

**Comment by Kevinjil** [comment]
This seems to be related to `HdHomerun` instead of this plugin.
