### ISSUE TITLE
Nothing showing up under LiveTV.

### ISSUE THREAD

**Issue by redredkrovy** [Kevinjil/Jellyfin.Xtream#139]
Jellyfin server 10.10.2
IPTVBoss for XC server

I've got the plugin installed along with my credentials and I've gone to LiveTV and checked every category.  I then hit save and the logs show this:

```
[13:49:02] [ERR] [43] Jellyfin.LiveTv.Guide.GuideManager: Error refreshing channels for service
System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.Net.Http.HttpIOException: The response ended prematurely. (ResponseEnded)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Jellyfin.Xtream.Client.XtreamClient.QueryApi[T](ConnectionInfo connectionInfo, String urlPath, CancellationToken cancellationToken)
   at Jellyfin.Xtream.Service.StreamService.GetLiveStreams(CancellationToken cancellationToken)+MoveNext()
   at Jellyfin.Xtream.Service.StreamService.GetLiveStreams(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Jellyfin.Xtream.Service.StreamService.GetLiveStreamsWithOverrides(CancellationToken cancellationToken)+MoveNext()
   at Jellyfin.Xtream.Service.StreamService.GetLiveStreamsWithOverrides(CancellationToken cancellationToken)+MoveNext()
   at Jellyfin.Xtream.Service.StreamService.GetLiveStreamsWithOverrides(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Jellyfin.Xtream.LiveTvService.GetChannelsAsync(CancellationToken cancellationToken)
   at Jellyfin.Xtream.LiveTvService.GetChannelsAsync(CancellationToken cancellationToken)
   at Jellyfin.LiveTv.Guide.GuideManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.Guide.GuideManager.RefreshGuide(IProgress`1 progress, CancellationToken cancellationToken)
[13:49:02] [INF] [43] Jellyfin.LiveTv.Guide.GuideManager: Refreshing guide with 7 days of guide data
[13:49:02] [INF] [43] Emby.Server.Implementations.ScheduledTasks.TaskManager: Refresh Guide Completed after 0 minute(s) and 3 seconds
```

Going to LiveTV on Jellyfin just shows an empty guide and channels tab.

I know it's talking to my XC server because I can see in the logs for it that it's getting a request and filling it.  If it makes any difference I am using a docker image for jellyfin and iptvboss.

Kind of seems like an issue with maybe IPTVBoss dropping the connection but I'm using the same XC server settings on another IPTV player with no issues.  Clicking on TV Overrides just gives me a spinning circle with the same error in the logs.

Any suggestions?

**Comment by Kevinjil** [comment]
This does look like a networking issue somewhere in your deployment. Could you open a shell in your container and use `curl` to contact the Xtream API?

**Comment by redredkrovy** [comment]
Here are the results.
```
root@c34e81dc9aa1:~# curl -Lv "http://127.0.0.1:8001/player_api.php?username=USER1&password=838hxfwi3"
*   Trying 127.0.0.1:8001...
* Connected to 127.0.0.1 (127.0.0.1) port 8001 (#0)
> GET /player_api.php?username=USER1&password=838hxfwi3 HTTP/1.1
> Host: 127.0.0.1:8001
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 18 Dec 2024 23:27:20 GMT
< Content-type: application/json
< Content-length: 667
< 
{
  "user_info" : {
    "username" : "USER1",
    "password" : "838hxfwi3",
    "message" : "Enjoy.!!",
    "auth" : 1,
    "status" : "Active",
    "exp_date" : "1734551686",
    "is_trial" : "0",
    "active_cons" : 0,
    "created_at" : "1584243213",
    "max_connections" : "1",
    "allowed_output_formats" : [ "m3u8", "ts", "rtmp" ]
  },
  "server_info" : {
    "xui" : true,
    "version" : "1.5.12",
    "revision" : 2,
    "url" : "192.168.20.103",
    "port" : "8001",
    "https_port" : "80011",
    "server_protocol" : "http",
    "rtmp_port" : "8003",
    "timestamp_now" : 1734564440,
    "time_now" : "2024-12-18 23:27:20",
    "timezone" : "UTC"
  }
* Connection #0 to host 127.0.0.1 left intact
}root@c34e81dc9aa1:~# 
```

It's getting a 200 response back.  I also tried from my Jellyfin container and got the same results after changing the ip address of course.

```
root@jellyfin:/# curl -Lv "http://192.168.20.103:8001/player_api.php?username=USER1&password=838hxfwi3"
*   Trying 192.168.20.103:8001...
* Connected to 192.168.20.103 (192.168.20.103) port 8001
> GET /player_api.php?username=USER1&password=838hxfwi3 HTTP/1.1
> Host: 192.168.20.103:8001
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 18 Dec 2024 23:29:19 GMT
< Content-type: application/json
< Content-length: 667
< 
{
  "user_info" : {
    "username" : "USER1",
    "password" : "838hxfwi3",
    "message" : "Enjoy.!!",
    "auth" : 1,
    "status" : "Active",
    "exp_date" : "1734551686",
    "is_trial" : "0",
    "active_cons" : 0,
    "created_at" : "1584243213",
    "max_connections" : "1",
    "allowed_output_formats" : [ "m3u8", "ts", "rtmp" ]
  },
  "server_info" : {
    "xui" : true,
    "version" : "1.5.12",
    "revision" : 2,
    "url" : "192.168.20.103",
    "port" : "8001",
    "https_port" : "80011",
    "server_protocol" : "http",
    "rtmp_port" : "8003",
    "timestamp_now" : 1734564559,
    "time_now" : "2024-12-18 23:29:19",
    "timezone" : "UTC"
  }
* Connection #0 to host 192.168.20.103 left intact
}root@jellyfin:/# 
```

Doing a get_live_categories request got me this response.

```
root@jellyfin:/# curl -Lv "http://192.168.20.103:8001/player_api.php?username=USER1&password=838hxfwi3&action=get_live_categories"
*   Trying 192.168.20.103:8001...
* Connected to 192.168.20.103 (192.168.20.103) port 8001
> GET /player_api.php?username=USER1&password=838hxfwi3&action=get_live_categories HTTP/1.1
> Host: 192.168.20.103:8001
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 18 Dec 2024 23:34:48 GMT
< Content-type: application/json
< Content-length: 1227
< 
[ {
  "category_id" : "12",
  "category_name" : "US| NBC HD/4K",
  "parent_id" : 0
}, {
  "category_id" : "2",
  "category_name" : "US| ABC HD/4K",
  "parent_id" : 0
}, {
  "category_id" : "3",
  "category_name" : "US| CBS HD/4K",
  "parent_id" : 0
}, {
  "category_id" : "9",
  "category_name" : "US| FOX HD/4K",
  "parent_id" : 0
}, {
  "category_id" : "7",
  "category_name" : "US| CW HD/4K",
  "parent_id" : 0
}, {
  "category_id" : "10",
  "category_name" : "US| KIDS HD/4K",
  "parent_id" : 0
}, {
  "category_id" : "8",
  "category_name" : "US| ENTERTAINMENT HD/4K",
  "parent_id" : 0
}, {
  "category_id" : "11",
  "category_name" : "US| MOVIES HD/4K",
  "parent_id" : 0
}, {
  "category_id" : "1",
  "category_name" : "US| 24/7 PPV TV",
  "parent_id" : 0
}, {
  "category_id" : "16",
  "category_name" : "US| PARAMOUNT+ ᴿᴬᵂ",
  "parent_id" : 0
}, {
  "category_id" : "18",
  "category_name" : "US| PEACOCK HD/4K",
  "parent_id" : 0
}, {
  "category_id" : "4",
  "category_name" : "US| CHRISTMAS",
  "parent_id" : 0
}, {
  "category_id" : "5",
  "category_name" : "US| CINEMA TV SHOWS HD/4K",
  "parent_id" : 0
}, {
  "category_id" : "6",
  "category_name" : "US| CINEMANIA HOLLYWOOD HD/4K",
  "parent_id" : 0
* Connection #0 to host 192.168.20.103 left intact
} ]
root@jellyfin:/# 
```

Seems like I'm getting a 200 response on both request and the info is being delivered.

**Comment by redredkrovy** [comment]
I'm also having the issue mentioned [here](https://github.com/Kevinjil/Jellyfin.Xtream/issues/123#issuecomment-2419562331).  Could the problem be related to the issue mentioned in that thread?  Something to do with the Jellyfin model and controller dependencies needing updated as Ratgen pointed out.

**Comment by Kevinjil** [comment]
> I'm also having the issue mentioned [here](https://github.com/Kevinjil/Jellyfin.Xtream/issues/123#issuecomment-2419562331). Could the problem be related to the issue mentioned in that thread? Something to do with the Jellyfin model and controller dependencies needing updated as Ratgen pointed out.

Unfortunately, that is unrelated. As of now, I have no clue why your setup is not working.

**Comment by redredkrovy** [comment]
Well I've had some success.  I changed over from IPTVBoss to IPTVEditor.  Using their XC stream link I can get the channels to show up but I'm only getting EPG data for some of the channels.  For the others I seem to be getting the error below.

```
[21:00:36] [ERR] [74] Jellyfin.LiveTv.Guide.GuideManager: Error getting programs for channel US: STARZ COMEDY HD
System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Jellyfin.Xtream.Client.XtreamClient.QueryApi[T](ConnectionInfo connectionInfo, String urlPath, CancellationToken cancellationToken)
   at Jellyfin.Xtream.LiveTvService.GetProgramsAsync(String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.Guide.GuideManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)
[21:00:37] [ERR] [69] Jellyfin.LiveTv.Guide.GuideManager: Error getting programs for channel US: STARZ EAST HD
System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Jellyfin.Xtream.Client.XtreamClient.QueryApi[T](ConnectionInfo connectionInfo, String urlPath, CancellationToken cancellationToken)
   at Jellyfin.Xtream.LiveTvService.GetProgramsAsync(String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.Guide.GuideManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)
[21:00:37] [ERR] [74] Jellyfin.LiveTv.Guide.GuideManager: Error getting programs for channel US: STARZ WEST HD
System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Jellyfin.Xtream.Client.XtreamClient.QueryApi[T](ConnectionInfo connectionInfo, String urlPath, CancellationToken cancellationToken)
   at Jellyfin.Xtream.LiveTvService.GetProgramsAsync(String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.Guide.GuideManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)
```

Maybe their server has some sort of DDOS protection and the plugin is exceeding the limit?

On a side note where should my VOD and Series channels show up at?  I've made sure to check mark "Show this channel to users" but I can't find them anywhere.  Should they be under the LiveTV area or somewhere else?

**Comment by redredkrovy** [comment]
I sort of figured out the issue with IPTVBoss.  It's not an issue on your end.  I had multiple categories so I went through and added them one by one.  I found three that for some reason IPTVBoss closed the connection early on.  So looks like an issue with IPTVBoss not the plugin.

Sorry to bother you.
