### ISSUE TITLE
Getting a 429 response when refreshing guide using IPTVEditor

### ISSUE THREAD

**Issue by redredkrovy** [Kevinjil/Jellyfin.Xtream#142]
Getting this error when refreshing guide.  Using IPTVEditor and Jellyfin 10.10.2.  Over half my guide is empty.

```
[14:37:29] [ERR] [123] Jellyfin.LiveTv.Guide.GuideManager: Error getting programs for channel BROOKLYN NINE-NINE 4K
System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Jellyfin.Xtream.Client.XtreamClient.QueryApi[T](ConnectionInfo connectionInfo, String urlPath, CancellationToken cancellationToken)
   at Jellyfin.Xtream.LiveTvService.GetProgramsAsync(String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.Guide.GuideManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)
```

Does this seem like a plugin issue where it's making request too fast?

**Comment by Kevinjil** [comment]
Your server limits API usage, which I am not willing to work around.
